version: '3.8'

services:
  taskseeder:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: taskseeder
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      # Persist SQLite database
      - taskseeder_data:/app/data
    environment:
      - NODE_ENV=production
      - PORT=3000
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/api/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      # Labels for reverse proxy (nginx, traefik, etc.)
      - "traefik.enable=true"
      - "traefik.http.routers.taskseeder.rule=Host(`taskseeder.yourdomain.com`)"
      - "traefik.http.routers.taskseeder.tls=true"
      - "traefik.http.routers.taskseeder.tls.certresolver=letsencrypt"
      - "traefik.http.services.taskseeder.loadbalancer.server.port=3000"

volumes:
  taskseeder_data:
    driver: local

networks:
  default:
    name: taskseeder_network